### ISSUE TITLE
TypeError failed to fetch

### ISSUE THREAD

**Issue by bygui86** [soberkoder/swaggo-orders-api#1]
Hi, first of all thank you for the tutorial, it's great. Looking forward your comparison between swaggo and go-swagger.

Unfortunately I'm not able to run your orders example.

When I try to make a getOrders request from SwaggerUI, I get this error:
<img width="1452" alt="get-orders" src="https://user-images.githubusercontent.com/22518997/84566487-ccf8f980-ad71-11ea-9b51-f0e98d97af2b.png">

Same when I try to perform a createOrder:
<img width="1452" alt="create-order" src="https://user-images.githubusercontent.com/22518997/84566488-cec2bd00-ad71-11ea-9818-1cfaee8c49ca.png">

I tried to build my own example, and I get the same error performing request getBlogPost.
[Here](https://github.com/bygui86/go-swagger) you can find my repo with my examples.

Have you ever had this issue? Can you help me fixing this?

**Comment by soberkoder** [comment]
Hi @bygui86 ,
Thanks for sharing the details. The issue was happening since the value for the `@host` annotation is incorrect. It was `localhost` earlier, and it should've been `localhost:8080` ideally (since the service was listening to the port `8080`)

I've fixed this and verified that I'm able to successfully call the `getOrders` API. Please check from your side once as well.
I'm sorry I haven't taken a look at your repo, but I'm guessing the problem should be something similar. Do let me know if the issue persists.

**Comment by bygui86** [comment]
Thanks a lot @soberkoder for the quick response.

I checked a bit better and I find out that the issue was caused by Google Chrome cache :(
I noticed the missing of `:8080` in the @host annotation, but this was not working due to the stupid cache :(
Using the incognito more, everything works fine with `localhost:8080` on my own example.
